version: "3.8"

services:
  db:
    image: postgres:12.0
    environment:
      - POSTGRES_DB=brokeragedb_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: ./etc/docker/local/Dockerfile
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/brokeragedb_local
    depends_on:
      - db

volumes:
  postgres_data:
