BUY_ORDER_OPERATION = "BUY"
SELL_ORDER_OPERATION = "SELL"

SUPPORTED_ORDER_OPERATIONS = [BUY_ORDER_OPERATION, SELL_ORDER_OPERATION]


INSUFFICIENT_FUNDS_ERROR_KEY = "INSUFFICIENT_FUNDS"
INSUFFICIENT_STOCKS_ERROR_KEY = "INSUFFICIENT_STOCKS"
INVALID_OPERATION_ERROR_KEY = "INVALID_OPERATION"
